spring:
  application:
    name: E-commerce API
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: ecommerce_admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver